services:
  db:
    image: postgres:16
    container_name: anime_store
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: anime_store
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - devdojo_data:/var/lib/postgresql/data

volumes:
  devdojo_data: