server:
  error:
    include-stacktrace: on_param

spring:
  profiles:
    active: ${APP_PROFILE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  prometheus:
    metrics:
      export:
        enabled: true