server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://dpg-cu9ocs5umphs73cesp00-a.ohio-postgres.render.com:5432/db_anime_store
    username: root
    password: 2jaJCdLEs2binQtSGLdOsP6Bku3eI4TC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
